markdown: kramdown
kramdown:
  parse_block_html: true
name: 18F Methods
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge

sass:
  style: compressed

collections:
  methods:
    output: true
    permalink: /:path/
site:
  title: 18F Methods

description: The 18F Methods are a guide to putting human-centered design into practice.

repos:
- name: 18F Methods
  description: Main repository
  url: https://github.com/18F/methods

jekyll_get:
  - data: releases
    json: 'https://api.github.com/repos/18F/methods/releases'

plugins:
  - jekyll-last-modified-at
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from

google_analytics_ua: UA-
